# Generated by Django 2.0.13 on 2019-06-14 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationtouristplaces',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outstationcore.Place'),
        ),
        migrations.AlterField(
            model_name='onroutetouristplaces',
            name='place',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='outstationcore.Place'),
        ),
    ]
