# Generated by Django 2.0.13 on 2019-06-14 19:31

from django.db import migrations, models
import outstation.apps.core.enums
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0002_auto_20190614_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onroutetouristplaces',
            name='amenities',
            field=wagtail.core.fields.StreamField([('amenity', wagtail.core.blocks.StructBlock([('amenity_type', wagtail.core.blocks.CharBlock(choices=[(outstation.apps.core.enums.AmenitiesChoice('Lodging'), 'Lodging'), (outstation.apps.core.enums.AmenitiesChoice('Petrol Pump'), 'Petrol Pump'), (outstation.apps.core.enums.AmenitiesChoice('Eating Place'), 'Eating Place')], default=outstation.apps.core.enums.AmenitiesChoice('Lodging'), required=True)), ('location', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onroutetouristplaces',
            name='distance_from_origin',
            field=models.IntegerField(default=0, verbose_name='Distance From Origin (km)'),
        ),
        migrations.AlterField(
            model_name='outstationroutepage',
            name='total_distance',
            field=models.PositiveSmallIntegerField(verbose_name='Total distance (km)'),
        ),
    ]
