# Generated by Django 2.0.13 on 2019-06-15 05:12

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0003_auto_20190615_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onroutetouristplaces',
            name='amenities',
            field=wagtail.core.fields.StreamField([('amenity', wagtail.core.blocks.StructBlock([('amenity_type', wagtail.core.blocks.ChoiceBlock(choices=[('Lodging', 'Lodging'), ('Petrol Pump', 'Petrol Pump'), ('Eating Place', 'Eating Place')])), ('location', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, null=True),
        ),
    ]
