# Generated by Django 2.0.13 on 2019-06-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0004_auto_20190615_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='onroutetouristplaces',
            name='detour',
            field=models.CharField(max_length=100, null=True, verbose_name='Detour'),
        ),
        migrations.AddField(
            model_name='onroutetouristplaces',
            name='detour_distance',
            field=models.IntegerField(default=0, null=True, verbose_name='Detour from main route (km)'),
        ),
    ]
