# Generated by Django 2.0.13 on 2019-06-16 07:40

from django.db import migrations, models
import django.db.models.deletion
import outstation.apps.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0005_auto_20190615_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('amenity_type', models.CharField(choices=[('Lodging', 'Lodging'), ('Petrol Pump', 'Petrol Pump'), ('Eating Place', 'Eating Place')], default=outstation.apps.core.enums.AmenitiesChoice('Lodging'), max_length=50)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='onroutetouristplaces',
            name='detour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Detour'),
        ),
        migrations.AlterField(
            model_name='onroutetouristplaces',
            name='detour_distance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Detour from main route (km)'),
        ),
        migrations.AddField(
            model_name='amenities',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_amenities', to='outstationroute.OnRouteTouristPlaces'),
        ),
    ]
