# Generated by Django 2.0.13 on 2019-06-16 07:45

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0006_auto_20190616_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='place',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='places_amenities', to='outstationroute.OnRouteTouristPlaces'),
        ),
    ]
