# Generated by Django 2.0.13 on 2019-06-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0007_auto_20190616_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='place',
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
    ]
