# Generated by Django 2.0.13 on 2019-06-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outstationroute', '0008_auto_20190616_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onroutetouristplaces',
            name='detour_distance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Detour from main route (km)'),
        ),
    ]
