# Generated by Django 2.0.13 on 2019-06-14 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outstationauth', '0001_initial'),
        ('outstationroute', '0001_initial'),
        ('outstationreview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_review', to='outstationroute.OutstationRoutePage'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='outstationauth.UserProfile'),
        ),
    ]
