# Generated by Django 2.0.13 on 2019-06-14 11:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('seater', models.PositiveSmallIntegerField(default=0)),
                ('per_km_rate', models.PositiveSmallIntegerField(default=0)),
                ('vehicle_feature', models.CharField(choices=[('AC', 'AC'), ('Non AC', 'Non AC')], default='AC', max_length=6)),
            ],
            options={
                'verbose_name_plural': 'Fares',
                'verbose_name': 'Fare',
            },
        ),
        migrations.CreateModel(
            name='LocationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Location tag', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Location Tags',
                'verbose_name': 'Location Tag',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.TextField(help_text='Add place details')),
                ('duration_of_visit', models.DurationField(default='00:05:00', help_text='[DD] [HH:[MM:]]ss[.uuuuuu] format', verbose_name='timeslot_duration')),
                ('location_tags', modelcluster.fields.ParentalManyToManyField(to='outstationcore.LocationTag')),
                ('map_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='PlaceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('place', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_images', to='outstationcore.Place')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(help_text='Trip type', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Trip Types',
                'verbose_name': 'Trip Type',
            },
        ),
        migrations.AddField(
            model_name='place',
            name='trip_types',
            field=modelcluster.fields.ParentalManyToManyField(to='outstationcore.TripType'),
        ),
    ]
