# Generated by Django 2.0.13 on 2019-06-15 07:37

from django.db import migrations, models
import outstation.apps.core.enums


class Migration(migrations.Migration):

    dependencies = [
        ('outstationcore', '0004_auto_20190615_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faretable',
            name='vehicle_feature',
            field=models.CharField(choices=[('AC', 'AC'), ('Non AC', 'NON - AC')], default=outstation.apps.core.enums.VehicleFeatureChoice('AC'), max_length=20),
        ),
        migrations.AlterField(
            model_name='faretable',
            name='vehicle_type',
            field=models.CharField(choices=[('HATCHBACK', 'HATCHBACK'), ('SEDAN', 'SEDAN'), ('SUV', 'SUV'), ('MINIBUS', 'MINIBUS'), ('SEDAN - PREMIUM', 'SEDAN - PREMIUM'), ('SEDAN - BUSINEESS CLASS', 'SEDAN - BUSINESS'), ('LUXURY', 'LUXURY')], default=outstation.apps.core.enums.VehicleTypeChoice('HATCHBACK'), max_length=50),
        ),
    ]
