# Generated by Django 2.0.13 on 2019-06-17 13:15

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationcore', '0006_popularroute_routelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteInRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('popular_routes', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_routes_links', to='outstationcore.PopularRoutes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='routelink',
            name='popular_route',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_in_region', to='outstationcore.RouteInRegion'),
        ),
        migrations.DeleteModel(
            name='PopularRoute',
        ),
    ]
