# Generated by Django 2.0.13 on 2019-06-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outstationcore', '0007_auto_20190617_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='popularroutes',
            options={'verbose_name': 'Popular Route', 'verbose_name_plural': 'Popular Routes'},
        ),
    ]
