# Generated by Django 2.0.13 on 2019-06-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outstationcore', '0008_auto_20190617_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeinregion',
            name='region',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='routelink',
            name='route',
            field=models.CharField(max_length=200),
        ),
    ]
