# Generated by Django 2.0.13 on 2019-06-17 14:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationcore', '0009_auto_20190617_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeinregion',
            name='popular_routes',
        ),
        migrations.AddField(
            model_name='popularroutes',
            name='region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='routelink',
            name='popular_route',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_in_region', to='outstationcore.PopularRoutes'),
        ),
        migrations.DeleteModel(
            name='RouteInRegion',
        ),
    ]
