# Generated by Django 2.0.13 on 2019-06-17 16:13

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('outstationcore', '0010_auto_20190617_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routelink',
            old_name='route',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='routelink',
            old_name='route_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='routelink',
            name='popular_route',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='outstationcore.PopularRoutes'),
        ),
    ]
